"""add FailureReasons column to WorkflowInstance

Revision ID: e3280edb70e5
Revises: f39de612b9e8
Create Date: 2025-10-23 10:45:07.247167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3280edb70e5'
down_revision: Union[str, Sequence[str], None] = 'f39de612b9e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('WorkflowInstance', sa.Column('FailureReasons', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('WorkflowInstance', 'FailureReasons')
    # ### end Alembic commands ###
